trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'go-vote-app'
  azureContainerRegistry: 'go-vote-app'
  azureSubscriptionEndpoint: 'go-vote-app'

steps:
- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerHub'
