trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'go-vote-app'
  dockerHub: 'dockerHub'
 
steps:
- task: Docker@2
  displayName: Build image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile 
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: |
      $(dockerHub)
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2
