trigger:
- master

pool:
  vmImage: 'Ubuntu-latest'

variables:
  imageName: 'go-vote-app'
  azureContainerRegistry: 'go-vote-app'
  azureSubscriptionEndpoint: 'go-vote-app'

steps:
- task: DockerCompose@1
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
