trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'go-vote-app:$(build.buildId)'
 
steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build'
- task: Docker@2
  displayName: 'Push image'
  inputs:
    containerRegistry:$(dockerHub)
  repository: $(imageName)
  command: push
  tags: |
    test1
    test2
